import type { Article } from './article-card';

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'El Futuro de la Tokenización de Activos Reales (RWA)',
    description: 'Exploramos cómo la tokenización de activos del mundo real está revolucionando las finanzas tradicionales...',
    imageUrl: '/rwa.png',
    imageHint: 'blockchain finance',
    category: 'DeFi',
    date: '4 de Mayo, 2025',
    isExclusive: false,
  },
  {
    id: '2',
    title: 'Estrategias Avanzadas de Staking en Ethereum',
    description: 'Un análisis profundo de las mejores estrategias para maximizar tus recompensas de staking en la red Ethereum post-Merge.',
    imageUrl: '/ethereum.png',
    imageHint: 'ethereum network',
    category: 'Staking',
    date: '18 de Mayo, 2025',
    isExclusive: true,
  },
  {
    id: '3',
    title: 'Introducción a los Oráculos Descentralizados',
    description: '¿Cómo obtienen los smart contracts datos del mundo real? Una guía completa sobre el funcionamiento y la importancia de los oráculos.',
    imageUrl: '/oraculos.png',
    imageHint: 'data network',
    category: 'Tecnología',
    date: '22 de Mayo, 2025',
    isExclusive: false,
  },
  {
    id: '4',
    title: 'Análisis Comparativo: Solana vs. Aptos',
    description: 'Ponemos frente a frente a dos de las blockchains de alto rendimiento más prometedoras. ¿Cuál tiene mayor potencial?',
    imageUrl: '/sol_aptos.png',
    imageHint: 'data comparison',
    category: 'Análisis',
    date: '1 de Junio, 2025',
    isExclusive: false,
  },
   {
    id: '5',
    title: 'Modelos de Gobernanza en DAOs: Lecciones Aprendidas',
    description: 'Estudiamos los modelos de gobernanza más exitosos y los fracasos más sonados en el mundo de las DAOs para extraer lecciones clave.',
    imageUrl: '/dao.png',
    imageHint: 'organization chart',
    category: 'Gobernanza',
    date: '5 de Junio, 2025',
    isExclusive: true,
  },
  {
    id: '6',
    title: 'Seguridad en Billeteras de Criptomonedas',
    description: 'Una guía práctica con las mejores prácticas para mantener tus activos digitales seguros, desde billeteras calientes hasta frías.',
    imageUrl: '/seguridad.png',
    imageHint: 'digital security',
    category: 'Seguridad',
    date: '17 de Junio, 2025',
    isExclusive: false,
  },
  {
    id: '7',
    title: 'Layer 2: Optimistic Rollups vs. ZK-Rollups en Ethereum',
    description: 'Cuales son las diferencias, cual es mejor para cada caso de uso y porque deberiamos conocerlas?',
    imageUrl: '/layer2.png',
    imageHint: 'Layers ',
    category: 'Tecnologia',
    date: '26 de Junio, 2025',
    isExclusive: false,
  },
  {
    id: '8',
    title: 'Interoperabilidad Blockchain: Puentes Cross-Chain y sus Riesgos',
    description: 'Cada cadena es un mundo y para viajar entre mundos, existen puentes que te ayudan a transportarte.',
    imageUrl: '/crosschain.png',
    imageHint: 'Puentes',
    category: 'DeFi',
    date: '1 de Julio, 2025',
    isExclusive: true,
  },
  {
    id: '9',
    title: 'DeFi 2.0: Más Allá de los Yield Farms Tradicionales',
    description: 'No todo en esta vida es Yield, existen muchas otras formas de poner a trabajar tus activos.',
    imageUrl: '/defi2.png',
    imageHint: 'Staking',
    category: 'Staking',
    date: '15 de Julio, 2025',

    isExclusive: false,
  },
  {
    id: '10',
    title: 'Consenso Proof-of-Stake vs. Proof-of-Work: Eficiencia vs. Seguridad',
    description: 'Porque Son los reyes del concenso, pero que beneficios tienen y como funcionan?.',
    imageUrl: '/pow-vs-pos.png',
    imageHint: 'Concenso',
    category: 'Tecnologia',
    date: '2 de Agosto, 2025',
    isExclusive: false,
  },
  {
    id: '11',
    title: 'El Impacto Ambiental de las Criptomonedas: Mitos y Realidades',
    description: 'Si, la computacion contamina, pero la solución no es apagar todas las computadoras.',
    imageUrl: '/cript-amb.png',
    imageHint: 'Criptomonedas y Medio Ambiente',
    category: 'Analisis',
    date: '24 de Agosto, 2025',
    isExclusive: false,
  },

];
