import type { Article } from './article-card';

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'El Futuro de la Tokenización de Activos Reales (RWA)',
    description: 'Exploramos cómo la tokenización de activos del mundo real está revolucionando las finanzas tradicionales...',
    imageUrl: '/rwa.png',
    imageHint: 'blockchain finance',
    category: 'DeFi',
    date: '15 de Julio, 2024',
    isExclusive: false,
  },
  {
    id: '2',
    title: 'Estrategias Avanzadas de Staking en Ethereum',
    description: 'Un análisis profundo de las mejores estrategias para maximizar tus recompensas de staking en la red Ethereum post-Merge.',
    imageUrl: '/ethereum.png',
    imageHint: 'ethereum network',
    category: 'Staking',
    date: '12 de Julio, 2024',
    isExclusive: true,
  },
  {
    id: '3',
    title: 'Introducción a los Oráculos Descentralizados',
    description: '¿Cómo obtienen los smart contracts datos del mundo real? Una guía completa sobre el funcionamiento y la importancia de los oráculos.',
    imageUrl: '/oraculos.png',
    imageHint: 'data network',
    category: 'Tecnología',
    date: '8 de Julio, 2024',
    isExclusive: false,
  },
  {
    id: '4',
    title: 'Análisis Comparativo: Solana vs. Aptos',
    description: 'Ponemos frente a frente a dos de las blockchains de alto rendimiento más prometedoras. ¿Cuál tiene mayor potencial?',
    imageUrl: '/sol_aptos.png',
    imageHint: 'data comparison',
    category: 'Análisis',
    date: '5 de Julio, 2024',
    isExclusive: false,
  },
   {
    id: '5',
    title: 'Modelos de Gobernanza en DAOs: Lecciones Aprendidas',
    description: 'Estudiamos los modelos de gobernanza más exitosos y los fracasos más sonados en el mundo de las DAOs para extraer lecciones clave.',
    imageUrl: '/dao.png',
    imageHint: 'organization chart',
    category: 'Gobernanza',
    date: '1 de Julio, 2024',
    isExclusive: true,
  },
  {
    id: '6',
    title: 'Seguridad en Billeteras de Criptomonedas',
    description: 'Una guía práctica con las mejores prácticas para mantener tus activos digitales seguros, desde billeteras calientes hasta frías.',
    imageUrl: '/seguridad.png',
    imageHint: 'digital security',
    category: 'Seguridad',
    date: '28 de Junio, 2024',
    isExclusive: false,
  },
];
